DROP TABLE IF EXISTS users;
DROP ROLE IF EXISTS test;
DROP DATABASE IF EXISTS "PERNUser";

CREATE DATABASE "PERNUser";
\c PERNUser

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);